### ISSUE TITLE
生产环境的问题?

### ISSUE THREAD

**Issue by gwhzh21** [NewLifeX/NewLife.Cache#2]
大约是10-30G大小的数据。
这个可以用于正式的生产环境吗？
每个客户端只需要一个单例连接对象？

**Comment by nnhy** [comment]
这个是特殊定制的内存缓存，性能超过redis且支持多线程，但是数据存在于内存没有持久化。

建议你的场景优先考虑redis

**Comment by gwhzh21** [comment]
redis我也全是走的缓存。把它相关的保存全去掉了。
主要是因为我的数据有这种的，每分钟要更新300次左右，而且均在1K以上的。
还有这种的，大量的集合数据，大约在200K-20M之间。读的也不多，每分钟应该差不多才200-300。
至于redis，曾经死在这上面。序列化和反序列化很频繁，然后直接存的是json字符串，gc回收的时候，最后导致整服务牺牲。所以最后，直好存在本服务的内存里面，但是这样又有一个问题，更新不即时。多个服务。有点头痛。所以在找其它的方案来处理这个缓存一致性的问题。

**Comment by nnhy** [comment]
明白你的意思了。

首先，频繁更新的数据，可以直接使用redis。
然后较大数据（>1M）可以采取本地内存缓存，或者本地磁盘文件缓存等方式。对于更新及时问题，可能需要你把大数据拆开，譬如集合数据使用hash或者set等

**Comment by gwhzh21** [comment]
我明白了。我试下hash或者set，看看性能。因为读取在高峰期还是麻烦的。

**Comment by nnhy** [comment]
实际上，我们在存放100亿数据到redis的时候，并没有存放json，而是byte[]
在海量数据序列化是，json耗CPU太高太高太高了

**Comment by gwhzh21** [comment]
使用redis，经历了从入门到放弃。大部分存的多行数据放到一个list对象，序列化为json 字符串，大部分在10K以上。然后，在使用了一段时间，刚开始cpu有涨，还没有注意，终于半个月后，随着进一步的转redis的工作继续，终于一天在高峰期翻车了。后面就转用进程内缓存了。
